#
# Docker environment.
#
---

version: '3.7'

networks:
    docker-network:
        name: docker-network
        driver: bridge

services:
    caddy:
        hostname: 'caddy'
        build:
            context: './docker/caddy'
        environment:
            - SERVER_NAME=${MERCURE_SERVER_NAME}
            - DEBUG=${MERCURE_DEBUG}
            - MERCURE_PUBLISHER_JWT_KEY=${MERCURE_PUBLISHER_JWT_KEY}
            - MERCURE_PUBLISHER_JWT_ALG=${MERCURE_PUBLISHER_JWT_ALG}
            - MERCURE_SUBSCRIBER_JWT_KEY=${MERCURE_SUBSCRIBER_JWT_KEY}
            - MERCURE_SUBSCRIBER_JWT_ALG=${MERCURE_SUBSCRIBER_JWT_ALG}
            - MERCURE_EXTRA_DIRECTIVES=${MERCURE_EXTRA_DIRECTIVES}
        command: /usr/bin/caddy run --config /config/Caddyfile
        ports:
            - ${HTTP_PORT}:80
            - ${HTTPS_PORT}:443
        volumes:
            - ./docker/caddy/volumes/config:/config
            - ./docker/caddy/volumes/data:/data
        logging:
            options:
                max-size: "10m"
                max-file: "5"
        networks:
            - 'docker-network'
